services:
  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: munchora
    volumes:
      - munchora_postgres_data:/var/lib/postgresql/data

volumes:
  munchora_postgres_data:
    name: munchora_postgres_data